#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "nvs_flash.h"
#include "esp_log.h"
#include "ble_spp_client.h"
#include "adc.h"
#include "lcd.h"
#include "driver/gpio.h"
#include "esp_sleep.h"
#include "sleep.h"
#include "menu.h"
#include "button.h"
#include "ui/ui.h"  // Generated by SquareLine Studio

#define TAG "MAIN"


extern bool is_connect;

void app_main(void)
{
    ESP_LOGI(TAG, "Starting Application");

    // Initialize sleep module
    sleep_init();

    // Initialize NVS
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);

    // Initialize ADC and start tasks
    ESP_ERROR_CHECK(adc_init());
    adc_start_task();

    // Wait for ADC calibration
    while (!adc_is_calibrated()) {
        vTaskDelay(pdMS_TO_TICKS(100));
    }

    // Initialize BLE
    spp_client_demo_init();
    ESP_LOGI(TAG, "BLE Initialization complete");

    // Initialize LCD and LVGL
    lcd_init();

    // Start display tasks
    lcd_start_tasks();

    // Start sleep monitoring
    sleep_start_monitoring();

    // Initialize LVGL
    lv_init();
    
    // Initialize SquareLine Studio UI
    ui_init();

    // Main task can now sleep
    while (1) {
        sleep_check_inactivity(is_connect);

        vTaskDelay(pdMS_TO_TICKS(100));
    }
}

