#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "nvs_flash.h"
#include "esp_log.h"
#include "ble_spp_client.h"
#include "adc.h"
#include "lcd.h"
#include "driver/gpio.h"
#include "esp_sleep.h"
#include "sleep.h"
#include "button.h"
#include "ui/ui.h"  // Generated by SquareLine Studio
#include "vesc_config.h"
#include "main.h"

#define TAG "MAIN"
#define LVGL_TASK_PRIORITY        6
#define BLE_TASK_PRIORITY         9
#define ADC_TASK_PRIORITY         10
#define DISPLAY_UPDATE_PRIORITY   5
#define SLEEP_MONITOR_PRIORITY    4

extern bool is_connect;

// Global mutex definitions
SemaphoreHandle_t lvgl_mutex = NULL;
SemaphoreHandle_t ble_data_mutex = NULL;
SemaphoreHandle_t adc_mutex = NULL;

static void splash_timer_cb(lv_timer_t * timer)
{
    lv_disp_load_scr(ui_home_screen);  // Switch to home screen after timeout
}

void init_system_mutexes(void) {
    lvgl_mutex = xSemaphoreCreateMutex();
    ble_data_mutex = xSemaphoreCreateMutex();
    adc_mutex = xSemaphoreCreateMutex();

    if (!lvgl_mutex || !ble_data_mutex || !adc_mutex) {
        ESP_LOGE(TAG, "Failed to create mutexes");
        abort();
    }
}

void app_main(void)
{
    // Initialize sleep module
    sleep_init();

    // Initialize system mutexes
    init_system_mutexes();

    // Initialize NVS
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);

    // Initialize VESC configuration
    ESP_ERROR_CHECK(vesc_config_init());

    // Initialize ADC and start tasks
    ESP_ERROR_CHECK(adc_init());
    adc_start_task();

    // Wait for ADC calibration
    while (!adc_is_calibrated()) {
        vTaskDelay(pdMS_TO_TICKS(100));
    }

    // Initialize BLE
    spp_client_demo_init();
    ESP_LOGI(TAG, "BLE Initialization complete");

    // Initialize LCD and LVGL
    lcd_init();

    // Initialize SquareLine Studio UI
    ui_init();
    lv_disp_load_scr(ui_splash_screen);
    lv_timer_t * splash_timer = lv_timer_create(splash_timer_cb, 1000, NULL);
    lv_timer_set_repeat_count(splash_timer, 1);

    // Start button monitoring
    sleep_start_monitoring();

    // Keep main task alive with minimal CPU usage
    while(1) {
        vTaskDelay(pdMS_TO_TICKS(100));
    }
}

