// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_home_screen
void ui_home_screen_screen_init(void);
extern lv_obj_t * ui_home_screen;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Bar3;
// CUSTOM VARIABLES

// SCREEN: ui_shutdown_screen
void ui_shutdown_screen_screen_init(void);
extern lv_obj_t * ui_shutdown_screen;
extern lv_obj_t * ui_shutdown;
extern lv_obj_t * ui_Bar4;
// CUSTOM VARIABLES

// SCREEN: ui_detailed_home
void ui_detailed_home_screen_init(void);
extern lv_obj_t * ui_detailed_home;
extern lv_obj_t * ui_vesc_voltage;
extern lv_obj_t * ui_vesc_motor_current;
extern lv_obj_t * ui_battery_current;
extern lv_obj_t * ui_vesc_consumption;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

// SCREEN: ui_splash_screen
void ui_splash_screen_screen_init(void);
extern lv_obj_t * ui_splash_screen;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_38597039);    // assets/Design sem nome (1).png
LV_IMG_DECLARE(ui_img_gb_png);    // assets/GB.png
LV_IMG_DECLARE(ui_img_battery101_png);    // assets/battery101.png
LV_IMG_DECLARE(ui_img_battery_0_png);    // assets/battery_0.png
LV_IMG_DECLARE(ui_img_battery_100_png);    // assets/battery_100.png
LV_IMG_DECLARE(ui_img_106406083);    // assets/icons8-bluetooth-24.png

// FONTS
LV_FONT_DECLARE(ui_font_bebas120);
LV_FONT_DECLARE(ui_font_bebas25);
LV_FONT_DECLARE(ui_font_bebas30);
LV_FONT_DECLARE(ui_font_bebas_medium);
LV_FONT_DECLARE(ui_font_bebas_small);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
