// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_home_screen
void ui_home_screen_screen_init(void);
extern lv_obj_t * ui_home_screen;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_shutdown_screen
void ui_shutdown_screen_screen_init(void);
extern lv_obj_t * ui_shutdown_screen;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_shutdown;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_106406083);    // assets/icons8-bluetooth-24.png
LV_IMG_DECLARE(ui_img_battery_100_png);    // assets/battery_100.png
LV_IMG_DECLARE(ui_img_battery101_png);    // assets/battery101.png
LV_IMG_DECLARE(ui_img_battery_0_png);    // assets/battery_0.png

// FONTS
LV_FONT_DECLARE(ui_font_bebas120);
LV_FONT_DECLARE(ui_font_bebas_small);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
